version: "3.8"
services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stc_project
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - my-postgres-container:/var/lib/postgresql/data
  spring-boot:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres-container:5432/stc_project
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8082:8082"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  my-postgres-container:
  pgadmin-data: